//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailTemplateteService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branches()
        {
            this.EmailsTemplate = new HashSet<EmailsTemplate>();
        }
    
        public short branch_num { get; set; }
        public string name { get; set; }
        public int manager { get; set; }
        public string street_id { get; set; }
        public string street { get; set; }
        public short house_num { get; set; }
        public string entrance { get; set; }
        public short appart { get; set; }
        public short city_id { get; set; }
        public string city { get; set; }
        public int zipcode { get; set; }
        public int pobox { get; set; }
        public short po_cityid { get; set; }
        public string po_city { get; set; }
        public int po_zipcode { get; set; }
        public string prefix1 { get; set; }
        public int phonnum1 { get; set; }
        public string prefix2 { get; set; }
        public int phonnum2 { get; set; }
        public string dprefix { get; set; }
        public int dphonnum { get; set; }
        public bool authorized { get; set; }
        public bool allow_emp { get; set; }
        public string status { get; set; }
        public System.DateTime date_cre { get; set; }
        public int user_cre { get; set; }
        public System.DateTime date_mod { get; set; }
        public int user_mod { get; set; }
        public string inf_place { get; set; }
        public bool InternetCycleVisible { get; set; }
        public bool InscriptByOfer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailsTemplate> EmailsTemplate { get; set; }
    }
}
