//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailTemplateteService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class campains
    {
        public int mis_campain { get; set; }
        public string teur_campain { get; set; }
        public int oved_achrai { get; set; }
        public int heara { get; set; }
        public System.DateTime ta_hazana { get; set; }
        public int yozem { get; set; }
        public System.DateTime ta_idkun { get; set; }
        public int meadken { get; set; }
        public string status { get; set; }
        public int tz_oved { get; set; }
    }
}
